#cloud-config
users:
  - name: odde
    groups: sudo,adm,dialout,cdrom,floppy,tape,audio,dip,video,plugdev,users
    sudo: ALL=(ALL) NOPASSWD:ALL
    shell: /usr/bin/fish
    hashed_passwd: "$6$rounds=500000$Mc9/uQcOl9N.ryEg$mX.SW03Q/u/g7k53pn40qbCI789EfyfaCAuyfhxVRW1yrlp4frKCVYC7JiYodwYmdyVUWHHb7FtWmDPSppUY0."
    lock_passwd: false
    no_create_home: false
    ssh_authorized_keys:
      - {ssh_key}

ssh_pwauth: true
ssh_quiet_keygen: false
ssh_deletekeys: true
ssh_genkeytypes: [ed25519]

ntp:
  enabled: true
  ntp_client: chrony
  servers:
    - time.cloudflare.com

packages:
  - fish
  - libssl-dev
  - rustup
  - libpcsclite-dev
  - lld
  - binaryen
  - gcc
  - cmake
  - zip
  - unzip
  - sqlite3
  - libsqlite3-dev
  - pkg-config

package_update: true
package_upgrade: true
package_reboot_if_required: true

bootcmd:
  - mkdir -p /opt/odde
  - chmod 644 /etc/systemd/system/odde.service
  - chown odde:odde /opt/odde/config.toml

write_files:
  - path: /etc/systemd/system/odde.service
    content: |
      [Unit]
      Description=odde
      After=syslog.target network-online.target

      [Service]
      Type=simple
      User=odde
      WorkingDirectory=/opt/odde
      ExecStart=/opt/odde/odde
      Restart=on-failure
      RestartSec=5

      [Install]
      WantedBy=multi-user.target

  - path: /opt/odde/config.toml
    content: |
      [flora]
      keys = [
          "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIFamaMSy9k9G2+o0F5G7kr+exqK6Z14c5+fH86OMmScq",
          "sk-ssh-ed25519@openssh.com AAAAGnNrLXNzaC1lZDI1NTE5QG9wZW5zc2guY29tAAAAIMrTPjuR7ibYPv/BioHijYBYV8C3Oa3ACMptIXKLV8XyAAAAC3NzaDpwcmltYXJ5",
          "ecdsa-sha2-nistp384 AAAAE2VjZHNhLXNoYTItbmlzdHAzODQAAAAIbmlzdHAzODQAAABhBFVWgqDZvHz1nOQ9zsBf3KbYFO90Y7ZkyEAidJmzCjYQtJb/ZpFsVXNgTWcgQYD/diQ8vT5VbQDUXdIGtpmikSTUGYEzlwXGKgYOZsGBT3FdvjBWbi4fA88yTdIaewy1NA==",
      ]

runcmd:
  - systemctl daemon-reexec
  - systemctl daemon-reload
  - systemctl enable odde
  - systemctl start odde
  - systemctl status odde
  - curl https://sh.rustup.rs -sSf | sh -s -- -y
