[flora]
keys = [
    "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIFamaMSy9k9G2+o0F5G7kr+exqK6Z14c5+fH86OMmScq",
    "sk-ssh-ed25519@openssh.com AAAAGnNrLXNzaC1lZDI1NTE5QG9wZW5zc2guY29tAAAAIMrTPjuR7ibYPv/BioHijYBYV8C3Oa3ACMptIXKLV8XyAAAAC3NzaDpwcmltYXJ5",
    "ecdsa-sha2-nistp384 AAAAE2VjZHNhLXNoYTItbmlzdHAzODQAAAAIbmlzdHAzODQAAABhBFVWgqDZvHz1nOQ9zsBf3KbYFO90Y7ZkyEAidJmzCjYQtJb/ZpFsVXNgTWcgQYD/diQ8vT5VbQDUXdIGtpmikSTUGYEzlwXGKgYOZsGBT3FdvjBWbi4fA88yTdIaewy1NA==",
]
