#cloud-config
users:
  - name: odde
    plain_text_passwd: odde
    shell: /bin/bash
    sudo: ALL=(ALL) NOPASSWD:ALL
    groups: sudo
    lock_passwd: false
    no_create_home: false
    ssh_authorized_keys:
#keys

ssh_pwauth: true

ntp:
  enabled: true
  ntp_client: chrony
  servers:
    - time.cloudflare.com

packages:
  - fish
  - libssl-dev
  - lld
  - gcc
  - cmake

package_update: true
package_upgrade: true
package_reboot_if_required: true

write_files:
  - path: /etc/systemd/system/odde.service
    content: |
      [Unit]
      Description=odde
      After=syslog.target network-online.target

      [Service]
      Type=simple
      User=odde
      WorkingDirectory=/home/odde
      ExecStart=/home/odde/odde
      Restart=on-failure
      RestartSec=5

      [Install]
      WantedBy=multi-user.target

  - path: /home/odde/config.toml
    content: |
#config
