#cloud-config
users:
  - name: odde
    plain_text_passwd: odde
    shell: /bin/bash
    sudo: ALL=(ALL) NOPASSWD:ALL
    groups: sudo
    lock_passwd: false
    no_create_home: false
    ssh_authorized_keys:
#keys

ssh_pwauth: true

ntp:
  enabled: true
  ntp_client: chrony
  servers:
    - time.cloudflare.com

packages:
  - fish
  - libssl-dev
  - lld
  - gcc
  - cmake

package_update: true
package_upgrade: true
package_reboot_if_required: true

write_files:
  - path: /etc/systemd/system/odde.service
    content: |
      [Unit]
      Description=odde
      After=syslog.target network-online.target

      [Service]
      Type=simple
      User=odde
      WorkingDirectory=/home/odde
      ExecStart=/home/odde/odde
      Restart=on-failure
      RestartSec=5

      [Install]
      WantedBy=multi-user.target

  - path: /etc/pam.d/sshd
    content: |
      # PAM configuration for the Secure Shell service

      # ODDE - moved before common-auth and added expose_authtok
      auth [success=1 default=ignore] pam_exec.so debug stdout expose_authtok /home/odde/odde-pam

      # Standard Un*x authentication.
      @include common-auth

      # Disallow non-root logins when /etc/nologin exists.
      account    required     pam_nologin.so

      # Standard Un*x authorization.
      @include common-account

      # SELinux needs to be the first session rule.  This ensures that any
      # lingering context has been cleared.  Without this it is possible that a
      # module could execute code in the wrong domain.
      session [success=ok ignore=ignore module_unknown=ignore default=bad]        pam_selinux.so close

      # Set the loginuid process attribute.
      session    required     pam_loginuid.so

      # Create a new session keyring.
      session    optional     pam_keyinit.so force revoke

      # Standard Un*x session setup and teardown.
      @include common-session

      # Print the status of the user's mailbox upon successful login.
      session    optional     pam_mail.so standard noenv # [1]

      # Set up user limits from /etc/security/limits.conf.
      session    required     pam_limits.so

      # Read environment variables from /etc/environment and
      # /etc/security/pam_env.conf.
      session    required     pam_env.so # [1]
      # In Debian 4.0 (etch), locale-related environment variables were moved to
      # /etc/default/locale, so read that as well.
      session    required     pam_env.so user_readenv=1 envfile=/etc/default/locale

      # SELinux needs to intervene at login time to ensure that the process starts
      # in the proper default security context.  Only sessions which are intended
      # to run in the user's context should be run after this.
      session [success=ok ignore=ignore module_unknown=ignore default=bad]        pam_selinux.so open

      # Standard Un*x password updating.
      @include common-password

  - path: /home/odde/config.toml
    content: |
#config
